### ISSUE TITLE
No midi input/output

### ISSUE THREAD

**Issue by shawnsick** [hotchk155/arpie#33]
My Arpie has stopped sending MIDI notes, RX LED lights up when I play a note on my MIDI keyboard. Nothing appears to be going through the MIDI output even though the TX LED lights up when notes are received via the MIDI input or in hold/inst without keyboard. The LEDS for IC1 and IC2 show that there is life and I have selected the appropriate MIDI channels, I have tried different synths and MIDI cables and all the solders and resistors are fine but the problem remains.

**Comment by hotchk155** [comment]
Hi - I just replied to the question in the Tindie PM you sent. Cheers/Jason
